version: '3.6'
services:
  app:
    build:
      context: .
    ports: 
      - "5000:5000"
    container_name: appdev_m
    restart: "unless-stopped" 
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 250M
        reservations:
          cpus: "0.1"
          memory: 128M