apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptest-deployment
spec:
  selector:
    matchLabels:
      run: apptest
  replicas: 1
  template:
    metadata:
      labels: 
        run: apptest
    spec:
      containers:
        - name: apptest
          image: mmanzano86/apptest:latest
          ports:
            - containerPort: 5000
              name: apptestport
