apiVersion: v1
kind: Service
metadata: 
  name: apptest-service
  labels: 
    run: apptest
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    run: apptest