name: Docker Image CI

on:
  push:
    branches: [ "docker_tags" ]
  pull_request:
    branches: [ "docker_tags" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate tags
        id: docker_tags
        uses: ${{ secrets.DOCKERHUB_USERNAME }}/apptest/action-docker-tags@v0.1
        with:
          registries: |
            docker.io
            ghcr.io
            quay.io
    - uses: actions/checkout@v3
    -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: $${{ steps.docker_tags.outputs.tags }}
          
