name: Docker Image CI

on:
  push:
    branches: [ "docker_tags" ]
  pull_request:
    branches: [ "docker_tags" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/apptest
        tag-custom: latest
        tag-semver: |
          {{raw}}
    -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apptest:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/apptest:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

          
